### ISSUE TITLE
clarify "Lo-tech PDT Rollertec interface kit"

### ISSUE THREAD

**Issue by digiltd** [J1mbo/homebridge-rollertec-garage-door#1]
Hi, about once every six months I do a search for PDT Rollertec type information in the hope that I can find some clue as to how to communicate with it through home automation. Your repo is the first that has specifically mentioned PDT Rollertec. Whilst I use Home Assistant and Alexa, I am sure knowing how to do it with Homebridge (which I used to use and contributed to ha-bridge) will be enough for me to get it working in whatever. The key bit is controlling the door from the command line. 

Ideally I would like to use my rfxtrx433e to send the rolling code, but open to other solutions. I tried to find the _Lo-tech PDT Rollertec interface kit_ you mention, but can't find anything PDT specific on the Lo-Tech boards. Can you clarify (and ideally link) to the device you mean?

Or, are you talking about anything that can be wired into the Rollertec control unit and act as a switch for the COM terminals, i.e. almost anything with a GPIO (pi, arduino, ESP8266)?

![image](https://user-images.githubusercontent.com/5680968/115348135-290a8680-a1aa-11eb-9a56-771400304b19.png)
 
Or something else?

thanks

**Comment by J1mbo** [comment]
Thanks @digiltd for your interest. Info on the Lo-tech PCB set for the Rollertec (which consists of an RPi Hat and a daughter board for the Rollertec) will be released very shortly, along with a refresh of the Lo-tech site. I will post back here next few days.

**Comment by digiltd** [comment]
Cheers. So just to clarify, it is a way of installing some hardware to the Rollertec?

**Comment by J1mbo** [comment]
Yes, the PCB set provides convenient connection and isolation between the rollertec and the RPi really, nothing clever. It could be wired another way to GPIO if preferred.

**Comment by J1mbo** [comment]
@digiltd - if you're interested, I have put up some information about the interface kit here:
https://www.lo-tech.co.uk/wiki/index.php/Lo-tech_PDT_RollerTec_Interface

I am currently looking at fulfillment options for this kit as the PDT I think is a European market product only (currently Lo-tech products are sold via the US).

**Comment by digiltd** [comment]
Thanks, some useful info and i especially like the neat way you have hooked it all up. It is all a bit confusing though, the .co.uk website that sells products via the US texelec site, who in turn have a confusing map showing shipping only to "highlighted countries" https://texelec.com/shipping/

But I guess with a product with such a super niche use-case, you are targeting enthusiasts rather than mass market :)

Let me know if they become available. Cheers. Great work btw.

**Comment by J1mbo** [comment]
@digiltd - I've made the PCB Gerbers available [here](https://www.lo-tech.co.uk/product/pdt-rollertec-interface/).
